require 'luacov'
local _ = require 'moses'

context('Disabling aliases', function()

  test('Testing aliases', function()
    assert_not_nil(_.forEach)
    assert_not_nil(_.collect)
    assert_not_nil(_.inject)
    assert_not_nil(_.foldl)
    assert_not_nil(_.injectr)
    assert_not_nil(_.foldr)
    assert_not_nil(_.mapr) 
    assert_not_nil(_.maprr) 
    assert_not_nil(_.any)
    assert_not_nil(_.some) 
    assert_not_nil(_.find)
    assert_not_nil(_.filter) 
    assert_not_nil(_.discard) 
    assert_not_nil(_.every)
    assert_not_nil(_.takeWhile)
    assert_not_nil(_.rejectWhile) 
    assert_not_nil(_.shift)
    assert_not_nil(_.rmRange) 
    assert_not_nil(_.head) 
    assert_not_nil(_.take) 
    assert_not_nil(_.tail) 
    assert_not_nil(_.without) 
    assert_not_nil(_.unique)
    assert_not_nil(_.mirror) 
    assert_not_nil(_.join) 
    assert_not_nil(_.cache) 
    assert_not_nil(_.uid) 
    assert_not_nil(_.methods) 
    assert_not_nil(_.choose) 
    assert_not_nil(_.drop)
    assert_not_nil(_.defaults) 
  end)
  
end)