_G.MOSES_NO_ALIASES = true
local _ = require 'moses'

context('Object functions specs', function()
	
	test('Defining MOSES_NO_ALIASES before importing moses disable aliases', function()
		assert_nil(_.forEach)
		assert_nil(_.collect)
		assert_nil(_.inject)
		assert_nil(_.foldl)
		assert_nil(_.injectr)
		assert_nil(_.foldr)
		assert_nil(_.mapr) 
		assert_nil(_.maprr) 
		assert_nil(_.any)
		assert_nil(_.some) 
		assert_nil(_.find)
		assert_nil(_.filter) 
		assert_nil(_.discard) 
		assert_nil(_.every)
		assert_nil(_.takeWhile)
		assert_nil(_.rejectWhile) 
		assert_nil(_.shift)
		assert_nil(_.rmRange) 
		assert_nil(_.head) 
		assert_nil(_.take) 
		assert_nil(_.tail) 
		assert_nil(_.without) 
		assert_nil(_.unique) 
		assert_nil(_.count) 
		assert_nil(_.mirror) 
		assert_nil(_.join) 
		assert_nil(_.cache) 
		assert_nil(_.uId) 
		assert_nil(_.methods) 
		assert_nil(_.choose) 
		assert_nil(_.drop)
		assert_nil(_.defaults) 
	end)

end)